name: Deploy
# based on https://zellwk.com/blog/github-actions-deploy/
# secrets.SSH_PRIVATE_KEY → server private SSH key
# secrets.SSH_HOST → 
# secrets.SSH_USER → SSH user

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      placeholder:
        description: 'What do you want?'
        required: false
        default: 'Cookies!!!'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # env:
    #   SECRET: ${{ secrets.SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build project
        run: yarn install && yarn build
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/sites/sustainable-playground/